/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 小川记账接口文档 - version v1.0.0
 *
 * 小川记账接口文档
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'user.updateProfile': ['POST', '/user/updateProfile'],
  'user.updatePasswordByOld': ['POST', '/user/updatePasswordByOld'],
  'user.updatePasswordByCode': ['POST', '/user/updatePasswordByCode'],
  'file.uploadTempFile': ['POST', '/file/temp/upload'],
  'bill.updateBill': ['POST', '/bill/update'],
  'bill.deleteBill': ['POST', '/bill/delete'],
  'bill.addBill': ['POST', '/bill/add'],
  'auth.sendCode': ['POST', '/auth/sendCode'],
  'auth.loginByPhone': ['POST', '/auth/loginByPhone'],
  'auth.loginByPassword': ['POST', '/auth/loginByPassword'],
  'user.getProfile': ['GET', '/user/profile'],
  'user.hasPassword': ['GET', '/user/hasPassword'],
  'bill.getPaymentMethods': ['GET', '/bill/payment-methods'],
  'bill.getPageBillList': ['GET', '/bill/page-list'],
  'bill.getMonthlyStats': ['GET', '/bill/monthly-stats'],
  'bill.getBillDetail': ['GET', '/bill/detail'],
  'bill.getCategories': ['GET', '/bill/categories'],
  'ai.text': ['GET', '/ai/text'],
  'ai.ocr': ['GET', '/ai/ocr'],
  'ai.analysis': ['GET', '/ai/analysis']
};
