/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 小川记账接口文档 - version v1.0.0
 *
 * 小川记账接口文档
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'user.updateProfile': ['POST', '/user/profile/update'],
  'user.updatePasswordByOld': ['POST', '/user/password/update-by-old'],
  'user.updatePasswordByCode': ['POST', '/user/password/update-by-code'],
  'file.uploadTempFile': ['POST', '/file/temp/upload'],
  'bill.updateBill': ['POST', '/bill/update'],
  'bill.deleteBill': ['POST', '/bill/delete'],
  'bill.batchCreate': ['POST', '/bill/batchCreate'],
  'bill.addBill': ['POST', '/bill/add'],
  'auth.sendCode': ['POST', '/auth/send-code'],
  'auth.logout': ['POST', '/auth/logout'],
  'auth.loginByWechat': ['POST', '/auth/login-wechat'],
  'auth.loginByPhone': ['POST', '/auth/login-phone'],
  'auth.loginByPassword': ['POST', '/auth/login-password'],
  'user.getProfile': ['GET', '/user/profile'],
  'user.hasPassword': ['GET', '/user/has-password'],
  'statistics.getOverview': ['GET', '/statistics/overview'],
  'statistics.getDailyTrend': ['GET', '/statistics/daily-trend'],
  'statistics.getCategoryStats': ['GET', '/statistics/category'],
  'bill.getPaymentMethods': ['GET', '/bill/payment-methods'],
  'bill.getPageBillList': ['GET', '/bill/page-list'],
  'bill.getMonthlyStats': ['GET', '/bill/monthly-stats'],
  'bill.getBillDetail': ['GET', '/bill/detail'],
  'bill.getCategories': ['GET', '/bill/categories'],
  'ai.text': ['GET', '/ai/text'],
  'ai.ocr': ['GET', '/ai/ocr'],
  'ai.analysis': ['GET', '/ai/analysis']
};
