/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 小川记账接口文档 - version v1.0.0
 *
 * 小川记账接口文档
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'user.updateProfile': ['POST', '/user/profile/update'],
  'user.updatePhoneByPassword': ['POST', '/user/phone/update-by-password'],
  'user.updatePhoneByCode': ['POST', '/user/phone/update-by-code'],
  'user.getPhoneCode': ['POST', '/user/phone/code'],
  'user.bindPhone': ['POST', '/user/phone/bind'],
  'user.updatePasswordByOld': ['POST', '/user/password/update-by-old'],
  'user.updatePasswordByCode': ['POST', '/user/password/update-by-code'],
  'user.deleteAccount': ['POST', '/user/account/delete'],
  'preference.setPreference': ['POST', '/preference/set'],
  'preference.deletePreference': ['POST', '/preference/delete'],
  'message.markAsRead': ['POST', '/message/mark-read'],
  'message.markAllAsRead': ['POST', '/message/mark-all-read'],
  'file.uploadTempFile': ['POST', '/file/temp/upload'],
  'family.updateFamily': ['POST', '/family/update'],
  'family.transferOwner': ['POST', '/family/transfer-owner'],
  'family.removeMember': ['POST', '/family/remove-member'],
  'family.refreshInviteCode': ['POST', '/family/refresh-invite-code'],
  'family.leaveFamily': ['POST', '/family/leave'],
  'family.joinFamily': ['POST', '/family/join'],
  'family.handleJoinApply': ['POST', '/family/handle-apply'],
  'family.deleteFamily': ['POST', '/family/delete'],
  'family.createFamily': ['POST', '/family/create'],
  'budget.setBudget': ['POST', '/budget/set'],
  'bill.updateBill': ['POST', '/bill/update'],
  'bill.exportBill': ['POST', '/bill/export'],
  'bill.deleteBill': ['POST', '/bill/delete'],
  'bill.batchCreate': ['POST', '/bill/batchCreate'],
  'bill.addBill': ['POST', '/bill/add'],
  'auth.sendCode': ['POST', '/auth/send-code'],
  'auth.retrievePassword': ['POST', '/auth/retrieve-password'],
  'auth.logout': ['POST', '/auth/logout'],
  'auth.loginByWechat': ['POST', '/auth/login-wechat'],
  'auth.loginByPhone': ['POST', '/auth/login-phone'],
  'auth.loginByPassword': ['POST', '/auth/login-password'],
  'user.getProfile': ['GET', '/user/profile'],
  'user.hasPassword': ['GET', '/user/has-password'],
  'statistics.getOverview': ['GET', '/statistics/overview'],
  'statistics.getMembersStats': ['GET', '/statistics/members-bill'],
  'statistics.getDailyTrend': ['GET', '/statistics/daily-trend'],
  'statistics.getCategoryStats': ['GET', '/statistics/category'],
  'preference.getPreference': ['GET', '/preference/get'],
  'preference.getAllPreference': ['GET', '/preference/all'],
  'message.getUnreadCount': ['GET', '/message/unread-count'],
  'message.getMessageList': ['GET', '/message/page-list'],
  'file.getUploadToken': ['GET', '/file/upload-token'],
  'family.getPendingApplies': ['GET', '/family/pending-applies'],
  'family.getMyFamilies': ['GET', '/family/my-families'],
  'family.getMembers': ['GET', '/family/members'],
  'family.getFamilyDetail': ['GET', '/family/detail'],
  'budget.getCurrentBudget': ['GET', '/budget/current'],
  'bill.getPaymentMethods': ['GET', '/bill/payment-methods'],
  'bill.getPageBillList': ['GET', '/bill/page-list'],
  'bill.getMonthlyStats': ['GET', '/bill/monthly-stats'],
  'bill.getBillDetail': ['GET', '/bill/detail'],
  'bill.getCategories': ['GET', '/bill/categories'],
  'ai.text': ['GET', '/ai/text'],
  'ai.ocr': ['GET', '/ai/ocr'],
  'ai.analysis': ['GET', '/ai/analysis'],
  'budget.deleteBudget': ['DELETE', '/budget/delete']
};
