/* tslint:disable */
/* eslint-disable */
/**
 * 小川记账接口文档 - version v1.0.0
 *
 * 小川记账接口文档
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface BillMonthlyStatsDTO {
  /**
   * 月份，格式为YYYY-MM
   */
  month: string;
  /**
   * 家庭ID，用于查询家庭账单统计信息
   */
  familyId?: string;
}
export interface StatisticsCategoryDTO {
  /**
   * 月份，格式为YYYY-MM
   */
  month: string;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type: string;
  /**
   * 家庭ID，用于查询家庭账单统计信息
   */
  familyId?: string;
}
export interface MessageListDTO {
  /**
   * 消息类型：system-系统消息，family-家庭消息，bill-账单消息，budget-预算消息
   */
  type?: string;
  /**
   * 消息状态：0-未读，1-已读
   */
  status?: number;
  /**
   * 页码
   */
  page: number;
  /**
   * 每页数量
   */
  size: number;
}
export interface BillListDTO {
  /**
   * 开始日期
   */
  startDate?: string;
  /**
   * 结束日期
   */
  endDate?: string;
  /**
   * 分类 ID
   */
  categoryId?: string;
  /**
   * 账单类型：income-收入，expense-支出，空字符串：全部
   */
  type?: string;
  /**
   * 支付方式 ID
   */
  paymentMethodId?: string;
  /**
   * 最小金额
   */
  minAmount?: string;
  /**
   * 最大金额
   */
  maxAmount?: string;
  /**
   * 关键字模糊搜索，支持名称和备注
   */
  keyword?: string;
  /**
   * 页码
   */
  page: number;
  /**
   * 每页数量
   */
  size: number;
  /**
   * 家庭 ID，传入则查询家庭账单，不传则查询个人账单
   */
  familyId?: string;
}
export interface UserProfileUpdateDTO {
  /**
   * 用户 ID
   */
  userId?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 头像 URL
   */
  avatar?: string;
  /**
   * 性别：0-未知，1-男，2-女
   */
  gender?: string;
}
export interface UpdatePhoneByPasswordDTO {
  /**
   * 密码
   */
  password: string;
  /**
   * 新手机号
   */
  newPhone: string;
  /**
   * 新手机号验证码
   */
  newPhoneCode: string;
}
export interface UpdatePhoneByCodeDTO {
  /**
   * 旧手机号验证码
   */
  oldPhoneCode: string;
  /**
   * 新手机号
   */
  newPhone: string;
  /**
   * 新手机号验证码
   */
  newPhoneCode: string;
}
export interface BindPhoneDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码
   */
  code: string;
}
export interface UpdatePasswordByOldDTO {
  /**
   * 用户 ID
   */
  userId: string;
  /**
   * 旧密码
   */
  oldPassword: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface UpdatePasswordByCodeDTO {
  /**
   * 验证码
   */
  code: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface DeleteAccountDTO {
  /**
   * 手机验证码
   */
  code: string;
}
export interface UpdateFamilyDTO {
  /**
   * 家庭ID
   */
  id: string;
  /**
   * 家庭名称
   */
  name?: string;
  /**
   * 家庭图标
   */
  avatar?: string;
  /**
   * 家庭描述
   */
  description?: string;
}
export interface TransferOwnerDTO {
  /**
   * 家庭ID
   */
  familyId: string;
  /**
   * 新户主用户ID
   */
  targetUserId: string;
}
export interface RemoveMemberDTO {
  /**
   * 家庭ID
   */
  familyId: string;
  /**
   * 家庭成员记录ID
   */
  memberId: string;
}
export interface JoinFamilyDTO {
  /**
   * 家庭邀请码
   */
  inviteCode: string;
  /**
   * 申请备注
   */
  remark?: string;
}
export interface HandleJoinApplyDTO {
  /**
   * 申请ID
   */
  applyId: string;
  /**
   * 是否同意
   */
  approved: boolean;
}
export interface CreateFamilyDTO {
  /**
   * 家庭名称
   */
  name: string;
  /**
   * 家庭图标
   */
  avatar?: string;
  /**
   * 家庭描述
   */
  description?: string;
}
export interface UpdateBillDTO {
  /**
   * 账单 ID
   */
  id: string;
  /**
   * 账单名称
   */
  name?: string;
  /**
   * 分类 ID
   */
  categoryId?: string;
  /**
   * 支付方式 ID
   */
  paymentMethodId?: string;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type?: string;
  /**
   * 账单时间
   */
  time?: string;
  /**
   * 账单金额
   */
  amount?: string;
  /**
   * 账单备注
   */
  remark?: string;
  /**
   * 家庭 ID，为空则属于个人账单
   */
  familyId?: string;
}
export interface AddBillDTO {
  /**
   * 账单名称
   */
  name: string;
  /**
   * 分类 ID
   */
  categoryId: string;
  /**
   * 支付方式 ID
   */
  paymentMethodId?: string;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type: string;
  /**
   * 账单金额
   */
  amount: string;
  /**
   * 账单时间
   */
  time: string;
  /**
   * 账单备注
   */
  remark?: string;
  /**
   * 家庭 ID（可选）
   */
  familyId?: string;
  /**
   * 账单来源：manual-手动，ocr-图片识别，voice-语音
   */
  source?: string;
}
export interface BatchCreateBillDTO {
  /**
   * 账单列表
   */
  bills: AddBillDTO[];
}
export interface SendCodeDTO {
  /**
   * 手机号
   */
  phone: string;
}
export interface RetrievePasswordDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码
   */
  code: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface LoginByWechatDTO {
  /**
   * 微信登录 code
   */
  code: string;
}
export interface LoginByPhoneDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码
   */
  code: string;
}
export interface LoginByPasswordDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 密码
   */
  password: string;
}
export interface PreferenceSetDTO {
  /**
   * 偏好设置键
   */
  key: string;
  /**
   * 偏好设置值
   */
  value: string;
}
export interface PreferenceDeleteDTO {
  /**
   * 偏好设置键
   */
  key: string;
}
export interface ResultVoid {
  code?: number;
  message?: string;
  data?: null;
  timestamp?: number;
  success?: boolean;
}
export interface ResultBoolean {
  code?: number;
  message?: string;
  data?: boolean;
  timestamp?: number;
  success?: boolean;
}
export interface UserVO {
  /**
   * 用户 ID
   */
  id?: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 头像 URL
   */
  avatar?: string;
  /**
   * 性别：0-未知，1-男，2-女
   */
  gender?: string;
  /**
   * 状态：false-禁用，true-正常
   */
  status?: boolean;
  /**
   * 是否VIP
   */
  isVip?: boolean;
  /**
   * 最后登录时间
   */
  lastLoginTime?: string;
  /**
   * 创建时间
   */
  createTime?: string;
  /**
   * 更新时间
   */
  updateTime?: string;
}
export interface ResultUserVO {
  code?: number;
  message?: string;
  /**
   * 用户信息
   */
  data?: UserVO;
  timestamp?: number;
  success?: boolean;
}
export interface UnreadCountVO {
  /**
   * 总未读数
   */
  total?: number;
  /**
   * 家庭相关未读数
   */
  familyCount?: number;
}
export interface ResultUnreadCountVO {
  code?: number;
  message?: string;
  /**
   * 未读消息数量
   */
  data?: UnreadCountVO;
  timestamp?: number;
  success?: boolean;
}
export interface FamilyVO {
  /**
   * 家庭ID
   */
  id?: string;
  /**
   * 家庭名称
   */
  name?: string;
  /**
   * 家庭图标
   */
  avatar?: string;
  /**
   * 家庭描述
   */
  description?: string;
  /**
   * 户主ID
   */
  ownerId?: string;
  /**
   * 户主昵称
   */
  ownerNickname?: string;
  /**
   * 户主头像
   */
  ownerAvatar?: string;
  /**
   * 邀请码
   */
  inviteCode?: string;
  /**
   * 成员数量
   */
  memberCount?: number;
  /**
   * 当前用户是否户主
   */
  isOwner?: boolean;
  /**
   * 创建时间
   */
  createTime?: string;
}
export interface ResultListFamilyVO {
  code?: number;
  message?: string;
  data?: FamilyVO[];
  timestamp?: number;
  success?: boolean;
}
export interface PaymentMethodVO {
  /**
   * 支付方式 ID
   */
  id?: string;
  /**
   * 支付方式名称
   */
  name?: string;
  /**
   * 图标 URL
   */
  icon?: string;
  /**
   * 排序
   */
  sortOrder?: number;
  /**
   * 是否默认
   */
  isDefault?: boolean;
  /**
   * 用户 ID
   */
  userId?: string;
}
export interface ResultListPaymentMethodVO {
  code?: number;
  message?: string;
  data?: PaymentMethodVO[];
  timestamp?: number;
  success?: boolean;
}
export interface TempFileVO {
  /**
   * 临时文件ID
   */
  fileId?: string;
  /**
   * 临时文件大小
   */
  fileSize?: number;
  /**
   * 临时文件扩展名
   */
  fileExt?: string;
  /**
   * 临时文件访问URL
   */
  fileUrl?: string;
}
export interface ResultTempFileVO {
  code?: number;
  message?: string;
  /**
   * 临时文件信息
   */
  data?: TempFileVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultFamilyVO {
  code?: number;
  message?: string;
  /**
   * 家庭信息
   */
  data?: FamilyVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultString {
  code?: number;
  message?: string;
  data?: string;
  timestamp?: number;
  success?: boolean;
}
export interface FamilyJoinApplyVO {
  /**
   * 申请ID
   */
  id?: string;
  /**
   * 家庭ID
   */
  familyId?: string;
  /**
   * 家庭名称
   */
  familyName?: string;
  /**
   * 申请人用户ID
   */
  userId?: string;
  /**
   * 申请人昵称
   */
  userNickname?: string;
  /**
   * 申请人头像
   */
  userAvatar?: string;
  /**
   * 申请备注
   */
  remark?: string;
  /**
   * 申请状态：0待处理，1同意，2拒绝
   */
  status?: number;
  /**
   * 处理人用户ID
   */
  handleUserId?: string;
  /**
   * 处理时间
   */
  handleTime?: string;
  /**
   * 创建时间
   */
  createTime?: string;
}
export interface ResultFamilyJoinApplyVO {
  code?: number;
  message?: string;
  /**
   * 家庭加入申请信息
   */
  data?: FamilyJoinApplyVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultInteger {
  code?: number;
  message?: string;
  data?: number;
  timestamp?: number;
  success?: boolean;
}
export interface BillSyncDetailVO {
  /**
   * 批次中的索引（0-based）
   */
  index?: number;
  /**
   * 同步状态：SUCCESS / FAILED
   */
  status?: string;
  /**
   * 成功时返回服务器生成的 ID
   */
  billId?: string;
  /**
   * 失败时的错误原因
   */
  reason?: string;
}
export interface BatchSyncResultVO {
  /**
   * 总数
   */
  total?: number;
  /**
   * 成功数
   */
  successCount?: number;
  /**
   * 失败数
   */
  failedCount?: number;
  /**
   * 状态：ALL_SUCCESS / PARTIAL_SUCCESS / ALL_FAILED
   */
  status?: string;
  /**
   * 每条账单的同步详情
   */
  details?: BillSyncDetailVO[];
}
export interface ResultBatchSyncResultVO {
  code?: number;
  message?: string;
  data?: BatchSyncResultVO;
  timestamp?: number;
  success?: boolean;
}
export interface TokenVO {
  /**
   * 访问令牌
   */
  token?: string;
  /**
   * 过期时间（毫秒）
   */
  expireTime?: number;
  /**
   * 用户 ID
   */
  userId?: string;
  /**
   * 用户昵称
   */
  nickname?: string;
}
export interface ResultTokenVO {
  code?: number;
  message?: string;
  /**
   * 令牌响应
   */
  data?: TokenVO;
  timestamp?: number;
  success?: boolean;
}
export interface BillMonthlyStatsVO {
  /**
   * 月份，格式为YYYY-MM
   */
  month?: string;
  /**
   * 支出金额
   */
  expense?: string;
  /**
   * 收入金额
   */
  income?: string;
  /**
   * 结余金额
   */
  balance?: string;
}
export interface ResultBillMonthlyStatsVO {
  code?: number;
  message?: string;
  /**
   * 账单月度统计信息
   */
  data?: BillMonthlyStatsVO;
  timestamp?: number;
  success?: boolean;
}
export interface FamilyMemberStatsVO {
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 用户昵称
   */
  nickname?: string;
  /**
   * 用户头像
   */
  avatar?: string;
  /**
   * 支出金额
   */
  expense?: string;
  /**
   * 收入金额
   */
  income?: string;
  /**
   * 支出占比(%)
   */
  expensePercentage?: number;
  /**
   * 收入占比(%)
   */
  incomePercentage?: number;
  /**
   * 是否是户主
   */
  isOwner?: boolean;
}
export interface ResultListFamilyMemberStatsVO {
  code?: number;
  message?: string;
  data?: FamilyMemberStatsVO[];
  timestamp?: number;
  success?: boolean;
}
export interface DailyTrendVO {
  /**
   * 日期，格式为YYYY-MM-DD
   */
  date?: string;
  /**
   * 支出金额
   */
  expense?: string;
  /**
   * 收入金额
   */
  income?: string;
}
export interface ResultListDailyTrendVO {
  code?: number;
  message?: string;
  data?: DailyTrendVO[];
  timestamp?: number;
  success?: boolean;
}
export interface CategoryStatisticsVO {
  /**
   * 分类ID
   */
  categoryId?: string;
  /**
   * 分类名称
   */
  categoryName?: string;
  /**
   * 分类图标
   */
  categoryIcon?: string;
  /**
   * 金额
   */
  amount?: string;
  /**
   * 占比百分比
   */
  percentage?: number;
}
export interface ResultListCategoryStatisticsVO {
  code?: number;
  message?: string;
  data?: CategoryStatisticsVO[];
  timestamp?: number;
  success?: boolean;
}
export interface MessageVO {
  /**
   * 消息ID
   */
  id?: string;
  /**
   * 消息标题
   */
  title?: string;
  /**
   * 消息内容
   */
  content?: string;
  /**
   * 消息类型：system-系统消息，family-家庭消息，bill-账单消息，budget-预算消息
   */
  type?: string;
  /**
   * 消息状态：0未读，1已读
   */
  status?: number;
  /**
   * 相关ID
   */
  relatedId?: string;
  /**
   * 相关类型：family-家庭，bill-账单，budget-预算
   */
  relatedType?: string;
  /**
   * 创建时间
   */
  createTime?: string;
}
export interface IPageMessageVO {
  size?: number;
  records?: MessageVO[];
  total?: number;
  current?: number;
  /**
   * @deprecated
   */
  pages?: number;
}
export interface ResultIPageMessageVO {
  code?: number;
  message?: string;
  data?: IPageMessageVO;
  timestamp?: number;
  success?: boolean;
}
export interface UploadTokenVO {
  token?: string;
  key?: string;
  cdnUrl?: string;
  uploadUrl?: string;
  expireSeconds?: number;
}
export interface ResultUploadTokenVO {
  code?: number;
  message?: string;
  /**
   * 上传凭证
   */
  data?: UploadTokenVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultListFamilyJoinApplyVO {
  code?: number;
  message?: string;
  data?: FamilyJoinApplyVO[];
  timestamp?: number;
  success?: boolean;
}
export interface FamilyMemberVO {
  /**
   * 成员记录ID
   */
  id?: string;
  /**
   * 家庭ID
   */
  familyId?: string;
  /**
   * 用户ID
   */
  userId?: string;
  /**
   * 家庭内昵称
   */
  nickname?: string;
  /**
   * 用户昵称
   */
  userNickname?: string;
  /**
   * 用户头像
   */
  userAvatar?: string;
  /**
   * 是否户主
   */
  isOwner?: boolean;
  /**
   * 加入时间
   */
  joinTime?: string;
}
export interface ResultListFamilyMemberVO {
  code?: number;
  message?: string;
  data?: FamilyMemberVO[];
  timestamp?: number;
  success?: boolean;
}
export interface CategoryVO {
  /**
   * 分类 ID
   */
  id?: string;
  /**
   * 分类名称
   */
  name?: string;
  /**
   * 图标 URL
   */
  icon?: string;
  /**
   * 分类类型：income-收入，expense-支出
   */
  type?: string;
  /**
   * 排序
   */
  sortOrder?: number;
  /**
   * 是否默认
   */
  isDefault?: boolean;
  /**
   * 用户 ID
   */
  userId?: string;
}
export interface BillVO {
  /**
   * 账单 ID
   */
  id?: string;
  /**
   * 账单名称
   */
  name?: string;
  /**
   * 分类信息
   */
  category?: CategoryVO;
  /**
   * 支付方式信息
   */
  paymentMethod?: PaymentMethodVO;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type?: string;
  /**
   * 账单金额
   */
  amount?: string;
  /**
   * 账单时间
   */
  time?: string;
  /**
   * 账单备注
   */
  remark?: string;
  /**
   * 账单来源：manual-手动，ocr-图片识别，voice-语音
   */
  source?: string;
  /**
   * 家庭 ID
   */
  familyId?: string;
  /**
   * 家庭名称
   */
  familyName?: string;
  /**
   * 记账人用户ID
   */
  userId?: string;
  /**
   * 记账人昵称
   */
  userNickname?: string;
  /**
   * 记账人头像
   */
  userAvatar?: string;
}
export interface IPageBillVO {
  size?: number;
  records?: BillVO[];
  total?: number;
  current?: number;
  /**
   * @deprecated
   */
  pages?: number;
}
export interface ResultIPageBillVO {
  code?: number;
  message?: string;
  data?: IPageBillVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultBillVO {
  code?: number;
  message?: string;
  /**
   * 账单信息
   */
  data?: BillVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultListCategoryVO {
  code?: number;
  message?: string;
  data?: CategoryVO[];
  timestamp?: number;
  success?: boolean;
}
export interface AiAnalysisVO {
  /**
   * AI分析内容
   */
  content?: string;
  /**
   * 是否为缓存结果
   */
  cached?: boolean;
  /**
   * 今日剩余分析次数，-1表示无限制(VIP)
   */
  remainingCount?: number;
}
export interface ResultAiAnalysisVO {
  code?: number;
  message?: string;
  /**
   * AI分析结果
   */
  data?: AiAnalysisVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultRecordStringString {
  code?: number;
  message?: string;
  data?: Record<string, string>;
  timestamp?: number;
  success?: boolean;
}
declare global {
  interface Apis {
    user: {
      /**
       * ---
       *
       * [POST] 更新用户资料
       *
       * **path:** /user/profile/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 用户 ID
       *   userId?: string
       *   // 昵称
       *   nickname?: string
       *   // 头像 URL
       *   avatar?: string
       *   // 性别：0-未知，1-男，2-女
       *   gender?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updateProfile<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UserProfileUpdateDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updateProfile', Config>;
      /**
       * ---
       *
       * [POST] 通过密码验证更换手机号
       *
       * **path:** /user/phone/update-by-password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 密码
       *   password: string
       *   // 新手机号
       *   newPhone: string
       *   // 新手机号验证码
       *   newPhoneCode: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updatePhoneByPassword<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdatePhoneByPasswordDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updatePhoneByPassword', Config>;
      /**
       * ---
       *
       * [POST] 通过验证码更换手机号
       *
       * **path:** /user/phone/update-by-code
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 旧手机号验证码
       *   oldPhoneCode: string
       *   // 新手机号
       *   newPhone: string
       *   // 新手机号验证码
       *   newPhoneCode: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updatePhoneByCode<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdatePhoneByCodeDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updatePhoneByCode', Config>;
      /**
       * ---
       *
       * [POST] 获取手机验证码
       *
       * **path:** /user/phone/code
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getPhoneCode<Config extends Alova2MethodConfig<ResultVoid>>(
        config?: Config
      ): Alova2Method<ResultVoid, 'user.getPhoneCode', Config>;
      /**
       * ---
       *
       * [POST] 绑定手机号
       *
       * **path:** /user/phone/bind
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 验证码
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      bindPhone<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: BindPhoneDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.bindPhone', Config>;
      /**
       * ---
       *
       * [POST] 通过旧密码修改密码
       *
       * **path:** /user/password/update-by-old
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 用户 ID
       *   userId: string
       *   // 旧密码
       *   oldPassword: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updatePasswordByOld<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdatePasswordByOldDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updatePasswordByOld', Config>;
      /**
       * ---
       *
       * [POST] 通过验证码修改密码
       *
       * **path:** /user/password/update-by-code
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 验证码
       *   code: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updatePasswordByCode<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdatePasswordByCodeDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updatePasswordByCode', Config>;
      /**
       * ---
       *
       * [POST] 注销账号
       *
       * **path:** /user/account/delete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机验证码
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      deleteAccount<
        Config extends Alova2MethodConfig<ResultVoid> & {
          data: DeleteAccountDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultVoid, 'user.deleteAccount', Config>;
      /**
       * ---
       *
       * [GET] 获取用户资料
       *
       * **path:** /user/profile
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 用户信息
       *   data?: {
       *     // 用户 ID
       *     id?: string
       *     // 手机号
       *     phone?: string
       *     // 昵称
       *     nickname?: string
       *     // 头像 URL
       *     avatar?: string
       *     // 性别：0-未知，1-男，2-女
       *     gender?: string
       *     // 状态：false-禁用，true-正常
       *     status?: boolean
       *     // 是否VIP
       *     isVip?: boolean
       *     // 最后登录时间
       *     lastLoginTime?: string
       *     // 创建时间
       *     createTime?: string
       *     // 更新时间
       *     updateTime?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getProfile<Config extends Alova2MethodConfig<ResultUserVO>>(
        config?: Config
      ): Alova2Method<ResultUserVO, 'user.getProfile', Config>;
      /**
       * ---
       *
       * [GET] 检查是否设置了密码
       *
       * **path:** /user/has-password
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      hasPassword<Config extends Alova2MethodConfig<ResultBoolean>>(
        config?: Config
      ): Alova2Method<ResultBoolean, 'user.hasPassword', Config>;
    };
    message: {
      /**
       * ---
       *
       * [POST] 标记消息已读
       *
       * **path:** /message/mark-read
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 消息ID
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      markAsRead<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          params: {
            /**
             * 消息ID
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'message.markAsRead', Config>;
      /**
       * ---
       *
       * [POST] 全部标记已读
       *
       * **path:** /message/mark-all-read
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      markAllAsRead<Config extends Alova2MethodConfig<ResultBoolean>>(
        config?: Config
      ): Alova2Method<ResultBoolean, 'message.markAllAsRead', Config>;
      /**
       * ---
       *
       * [GET] 获取未读消息数量
       *
       * **path:** /message/unread-count
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 未读消息数量
       *   data?: {
       *     // 总未读数
       *     total?: number
       *     // 家庭相关未读数
       *     familyCount?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getUnreadCount<Config extends Alova2MethodConfig<ResultUnreadCountVO>>(
        config?: Config
      ): Alova2Method<ResultUnreadCountVO, 'message.getUnreadCount', Config>;
      /**
       * ---
       *
       * [GET] 获取消息列表
       *
       * **path:** /message/page-list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 消息列表查询参数
       *   dto?: {
       *     // 消息类型：system-系统消息，family-家庭消息，bill-账单消息，budget-预算消息
       *     type?: string
       *     // 消息状态：0-未读，1-已读
       *     status?: number
       *     // 页码
       *     page: number
       *     // 每页数量
       *     size: number
       *   }
       *   type?: string
       *   status?: number
       *   page?: number
       *   size?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: {
       *     size?: number
       *     // [items] start
       *     // 消息信息
       *     // [items] end
       *     records?: Array<{
       *       // 消息ID
       *       id?: string
       *       // 消息标题
       *       title?: string
       *       // 消息内容
       *       content?: string
       *       // 消息类型：system-系统消息，family-家庭消息，bill-账单消息，budget-预算消息
       *       type?: string
       *       // 消息状态：0未读，1已读
       *       status?: number
       *       // 相关ID
       *       relatedId?: string
       *       // 相关类型：family-家庭，bill-账单，budget-预算
       *       relatedType?: string
       *       // 创建时间
       *       createTime?: string
       *     }>
       *     total?: number
       *     current?: number
       *     // [deprecated]
       *     pages?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getMessageList<
        Config extends Alova2MethodConfig<ResultIPageMessageVO> & {
          params: {
            /**
             * 消息列表查询参数
             */
            dto?: MessageListDTO;
            type?: string;
            status?: number;
            page?: number;
            size?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultIPageMessageVO, 'message.getMessageList', Config>;
    };
    file: {
      /**
       * ---
       *
       * [POST] 上传临时文件
       *
       * **path:** /file/temp/upload
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   file: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 临时文件信息
       *   data?: {
       *     // 临时文件ID
       *     fileId?: string
       *     // 临时文件大小
       *     fileSize?: number
       *     // 临时文件扩展名
       *     fileExt?: string
       *     // 临时文件访问URL
       *     fileUrl?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      uploadTempFile<
        Config extends Alova2MethodConfig<ResultTempFileVO> & {
          params: {
            file: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultTempFileVO, 'file.uploadTempFile', Config>;
      /**
       * ---
       *
       * [GET] 获取上传凭证
       *
       * **path:** /file/upload-token
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 文件名
       *   fileName: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 上传凭证
       *   data?: {
       *     token?: string
       *     key?: string
       *     cdnUrl?: string
       *     uploadUrl?: string
       *     expireSeconds?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getUploadToken<
        Config extends Alova2MethodConfig<ResultUploadTokenVO> & {
          params: {
            /**
             * 文件名
             */
            fileName: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultUploadTokenVO, 'file.getUploadToken', Config>;
    };
    family: {
      /**
       * ---
       *
       * [POST] 更新家庭信息
       *
       * **path:** /family/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 家庭ID
       *   id: string
       *   // 家庭名称
       *   name?: string
       *   // 家庭图标
       *   avatar?: string
       *   // 家庭描述
       *   description?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 家庭信息
       *   data?: {
       *     // 家庭ID
       *     id?: string
       *     // 家庭名称
       *     name?: string
       *     // 家庭图标
       *     avatar?: string
       *     // 家庭描述
       *     description?: string
       *     // 户主ID
       *     ownerId?: string
       *     // 户主昵称
       *     ownerNickname?: string
       *     // 户主头像
       *     ownerAvatar?: string
       *     // 邀请码
       *     inviteCode?: string
       *     // 成员数量
       *     memberCount?: number
       *     // 当前用户是否户主
       *     isOwner?: boolean
       *     // 创建时间
       *     createTime?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updateFamily<
        Config extends Alova2MethodConfig<ResultFamilyVO> & {
          data: UpdateFamilyDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultFamilyVO, 'family.updateFamily', Config>;
      /**
       * ---
       *
       * [POST] 转让户主
       *
       * **path:** /family/transfer-owner
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 家庭ID
       *   familyId: string
       *   // 新户主用户ID
       *   targetUserId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      transferOwner<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: TransferOwnerDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'family.transferOwner', Config>;
      /**
       * ---
       *
       * [POST] 移除家庭成员
       *
       * **path:** /family/remove-member
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 家庭ID
       *   familyId: string
       *   // 家庭成员记录ID
       *   memberId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      removeMember<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: RemoveMemberDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'family.removeMember', Config>;
      /**
       * ---
       *
       * [POST] 刷新邀请码
       *
       * **path:** /family/refresh-invite-code
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 家庭ID
       *   familyId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: string
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      refreshInviteCode<
        Config extends Alova2MethodConfig<ResultString> & {
          params: {
            /**
             * 家庭ID
             */
            familyId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultString, 'family.refreshInviteCode', Config>;
      /**
       * ---
       *
       * [POST] 退出家庭
       *
       * **path:** /family/leave
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 家庭ID
       *   familyId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      leaveFamily<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          params: {
            /**
             * 家庭ID
             */
            familyId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'family.leaveFamily', Config>;
      /**
       * ---
       *
       * [POST] 申请加入家庭
       *
       * **path:** /family/join
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 家庭邀请码
       *   inviteCode: string
       *   // 申请备注
       *   remark?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 家庭加入申请信息
       *   data?: {
       *     // 申请ID
       *     id?: string
       *     // 家庭ID
       *     familyId?: string
       *     // 家庭名称
       *     familyName?: string
       *     // 申请人用户ID
       *     userId?: string
       *     // 申请人昵称
       *     userNickname?: string
       *     // 申请人头像
       *     userAvatar?: string
       *     // 申请备注
       *     remark?: string
       *     // 申请状态：0待处理，1同意，2拒绝
       *     status?: number
       *     // 处理人用户ID
       *     handleUserId?: string
       *     // 处理时间
       *     handleTime?: string
       *     // 创建时间
       *     createTime?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      joinFamily<
        Config extends Alova2MethodConfig<ResultFamilyJoinApplyVO> & {
          data: JoinFamilyDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultFamilyJoinApplyVO, 'family.joinFamily', Config>;
      /**
       * ---
       *
       * [POST] 处理加入申请
       *
       * **path:** /family/handle-apply
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 申请ID
       *   applyId: string
       *   // 是否同意
       *   approved: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      handleJoinApply<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: HandleJoinApplyDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'family.handleJoinApply', Config>;
      /**
       * ---
       *
       * [POST] 删除家庭
       *
       * **path:** /family/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 家庭ID
       *   familyId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      deleteFamily<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          params: {
            /**
             * 家庭ID
             */
            familyId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'family.deleteFamily', Config>;
      /**
       * ---
       *
       * [POST] 创建家庭
       *
       * **path:** /family/create
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 家庭名称
       *   name: string
       *   // 家庭图标
       *   avatar?: string
       *   // 家庭描述
       *   description?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 家庭信息
       *   data?: {
       *     // 家庭ID
       *     id?: string
       *     // 家庭名称
       *     name?: string
       *     // 家庭图标
       *     avatar?: string
       *     // 家庭描述
       *     description?: string
       *     // 户主ID
       *     ownerId?: string
       *     // 户主昵称
       *     ownerNickname?: string
       *     // 户主头像
       *     ownerAvatar?: string
       *     // 邀请码
       *     inviteCode?: string
       *     // 成员数量
       *     memberCount?: number
       *     // 当前用户是否户主
       *     isOwner?: boolean
       *     // 创建时间
       *     createTime?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      createFamily<
        Config extends Alova2MethodConfig<ResultFamilyVO> & {
          data: CreateFamilyDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultFamilyVO, 'family.createFamily', Config>;
      /**
       * ---
       *
       * [GET] 获取待处理的加入申请
       *
       * **path:** /family/pending-applies
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 家庭ID
       *   familyId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 家庭加入申请信息
       *   // [items] end
       *   data?: Array<{
       *     // 申请ID
       *     id?: string
       *     // 家庭ID
       *     familyId?: string
       *     // 家庭名称
       *     familyName?: string
       *     // 申请人用户ID
       *     userId?: string
       *     // 申请人昵称
       *     userNickname?: string
       *     // 申请人头像
       *     userAvatar?: string
       *     // 申请备注
       *     remark?: string
       *     // 申请状态：0待处理，1同意，2拒绝
       *     status?: number
       *     // 处理人用户ID
       *     handleUserId?: string
       *     // 处理时间
       *     handleTime?: string
       *     // 创建时间
       *     createTime?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getPendingApplies<
        Config extends Alova2MethodConfig<ResultListFamilyJoinApplyVO> & {
          params: {
            /**
             * 家庭ID
             */
            familyId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListFamilyJoinApplyVO, 'family.getPendingApplies', Config>;
      /**
       * ---
       *
       * [GET] 获取我的家庭列表
       *
       * **path:** /family/my-families
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 家庭信息
       *   // [items] end
       *   data?: Array<{
       *     // 家庭ID
       *     id?: string
       *     // 家庭名称
       *     name?: string
       *     // 家庭图标
       *     avatar?: string
       *     // 家庭描述
       *     description?: string
       *     // 户主ID
       *     ownerId?: string
       *     // 户主昵称
       *     ownerNickname?: string
       *     // 户主头像
       *     ownerAvatar?: string
       *     // 邀请码
       *     inviteCode?: string
       *     // 成员数量
       *     memberCount?: number
       *     // 当前用户是否户主
       *     isOwner?: boolean
       *     // 创建时间
       *     createTime?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getMyFamilies<Config extends Alova2MethodConfig<ResultListFamilyVO>>(
        config?: Config
      ): Alova2Method<ResultListFamilyVO, 'family.getMyFamilies', Config>;
      /**
       * ---
       *
       * [GET] 获取家庭成员列表
       *
       * **path:** /family/members
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 家庭ID
       *   familyId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 家庭成员信息
       *   // [items] end
       *   data?: Array<{
       *     // 成员记录ID
       *     id?: string
       *     // 家庭ID
       *     familyId?: string
       *     // 用户ID
       *     userId?: string
       *     // 家庭内昵称
       *     nickname?: string
       *     // 用户昵称
       *     userNickname?: string
       *     // 用户头像
       *     userAvatar?: string
       *     // 是否户主
       *     isOwner?: boolean
       *     // 加入时间
       *     joinTime?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getMembers<
        Config extends Alova2MethodConfig<ResultListFamilyMemberVO> & {
          params: {
            /**
             * 家庭ID
             */
            familyId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListFamilyMemberVO, 'family.getMembers', Config>;
      /**
       * ---
       *
       * [GET] 获取家庭详情
       *
       * **path:** /family/detail
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 家庭ID
       *   familyId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 家庭信息
       *   data?: {
       *     // 家庭ID
       *     id?: string
       *     // 家庭名称
       *     name?: string
       *     // 家庭图标
       *     avatar?: string
       *     // 家庭描述
       *     description?: string
       *     // 户主ID
       *     ownerId?: string
       *     // 户主昵称
       *     ownerNickname?: string
       *     // 户主头像
       *     ownerAvatar?: string
       *     // 邀请码
       *     inviteCode?: string
       *     // 成员数量
       *     memberCount?: number
       *     // 当前用户是否户主
       *     isOwner?: boolean
       *     // 创建时间
       *     createTime?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getFamilyDetail<
        Config extends Alova2MethodConfig<ResultFamilyVO> & {
          params: {
            /**
             * 家庭ID
             */
            familyId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultFamilyVO, 'family.getFamilyDetail', Config>;
    };
    bill: {
      /**
       * ---
       *
       * [POST] 更新账单
       *
       * **path:** /bill/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 账单 ID
       *   id: string
       *   // 账单名称
       *   name?: string
       *   // 分类 ID
       *   categoryId?: string
       *   // 支付方式 ID
       *   paymentMethodId?: string
       *   // 账单类型：income-收入，expense-支出
       *   type?: string
       *   // 账单时间
       *   time?: string
       *   // 账单金额
       *   amount?: string
       *   // 账单备注
       *   remark?: string
       *   // 家庭 ID，为空则属于个人账单
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updateBill<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdateBillDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'bill.updateBill', Config>;
      /**
       * ---
       *
       * [POST] 删除账单
       *
       * **path:** /bill/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单 ID
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      deleteBill<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          params: {
            /**
             * 账单 ID
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'bill.deleteBill', Config>;
      /**
       * ---
       *
       * [POST] 批量添加账单
       *
       * **path:** /bill/batchCreate
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 账单列表
       *   // [items] start
       *   // 添加账单请求
       *   // [items] end
       *   bills: Array<{
       *     // 账单名称
       *     name: string
       *     // 分类 ID
       *     categoryId: string
       *     // 支付方式 ID
       *     paymentMethodId?: string
       *     // 账单类型：income-收入，expense-支出
       *     type: string
       *     // 账单金额
       *     amount: string
       *     // 账单时间
       *     time: string
       *     // 账单备注
       *     remark?: string
       *     // 家庭 ID（可选）
       *     familyId?: string
       *     // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *     source?: string
       *   }>
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: {
       *     total?: number
       *     successCount?: number
       *     failedCount?: number
       *     status?: string
       *     details?: Array<{
       *       index?: number
       *       status?: string
       *       billId?: string
       *       reason?: string
       *     }>
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      batchCreate<
        Config extends Alova2MethodConfig<ResultBatchSyncResultVO> & {
          data: BatchCreateBillDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBatchSyncResultVO, 'bill.batchCreate', Config>;
      /**
       * ---
       *
       * [POST] 添加账单
       *
       * **path:** /bill/add
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 账单名称
       *   name: string
       *   // 分类 ID
       *   categoryId: string
       *   // 支付方式 ID
       *   paymentMethodId?: string
       *   // 账单类型：income-收入，expense-支出
       *   type: string
       *   // 账单金额
       *   amount: string
       *   // 账单时间
       *   time: string
       *   // 账单备注
       *   remark?: string
       *   // 家庭 ID（可选）
       *   familyId?: string
       *   // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *   source?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      addBill<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: AddBillDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'bill.addBill', Config>;
      /**
       * ---
       *
       * [GET] 获取支付方式列表
       *
       * **path:** /bill/payment-methods
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 支付方式信息
       *   // [items] end
       *   data?: Array<{
       *     // 支付方式 ID
       *     id?: string
       *     // 支付方式名称
       *     name?: string
       *     // 图标 URL
       *     icon?: string
       *     // 排序
       *     sortOrder?: number
       *     // 是否默认
       *     isDefault?: boolean
       *     // 用户 ID
       *     userId?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getPaymentMethods<Config extends Alova2MethodConfig<ResultListPaymentMethodVO>>(
        config?: Config
      ): Alova2Method<ResultListPaymentMethodVO, 'bill.getPaymentMethods', Config>;
      /**
       * ---
       *
       * [GET] 获取账单列表
       *
       * **path:** /bill/page-list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单列表查询参数
       *   billListDTO?: {
       *     // 开始日期
       *     startDate?: string
       *     // 结束日期
       *     endDate?: string
       *     // 分类 ID
       *     categoryId?: string
       *     // 账单类型：income-收入，expense-支出，空字符串：全部
       *     type?: string
       *     // 支付方式 ID
       *     paymentMethodId?: string
       *     // 最小金额
       *     minAmount?: string
       *     // 最大金额
       *     maxAmount?: string
       *     // 关键字模糊搜索，支持名称和备注
       *     keyword?: string
       *     // 页码
       *     page: number
       *     // 每页数量
       *     size: number
       *     // 家庭 ID，传入则查询家庭账单，不传则查询个人账单
       *     familyId?: string
       *   }
       *   startDate?: string
       *   endDate?: string
       *   categoryId?: string
       *   type?: string
       *   paymentMethodId?: string
       *   minAmount?: string
       *   maxAmount?: string
       *   keyword?: string
       *   page?: number
       *   size?: number
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: {
       *     size?: number
       *     // [items] start
       *     // 账单信息
       *     // [items] end
       *     records?: Array<{
       *       // 账单 ID
       *       id?: string
       *       // 账单名称
       *       name?: string
       *       // 分类信息
       *       category?: {
       *         // 分类 ID
       *         id?: string
       *         // 分类名称
       *         name?: string
       *         // 图标 URL
       *         icon?: string
       *         // 分类类型：income-收入，expense-支出
       *         type?: string
       *         // 排序
       *         sortOrder?: number
       *         // 是否默认
       *         isDefault?: boolean
       *         // 用户 ID
       *         userId?: string
       *       }
       *       // 支付方式信息
       *       paymentMethod?: {
       *         // 支付方式 ID
       *         id?: string
       *         // 支付方式名称
       *         name?: string
       *         // 图标 URL
       *         icon?: string
       *         // 排序
       *         sortOrder?: number
       *         // 是否默认
       *         isDefault?: boolean
       *         // 用户 ID
       *         userId?: string
       *       }
       *       // 账单类型：income-收入，expense-支出
       *       type?: string
       *       // 账单金额
       *       amount?: string
       *       // 账单时间
       *       time?: string
       *       // 账单备注
       *       remark?: string
       *       // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *       source?: string
       *       // 家庭 ID
       *       familyId?: string
       *       // 家庭名称
       *       familyName?: string
       *       // 记账人用户ID
       *       userId?: string
       *       // 记账人昵称
       *       userNickname?: string
       *       // 记账人头像
       *       userAvatar?: string
       *     }>
       *     total?: number
       *     current?: number
       *     // [deprecated]
       *     pages?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getPageBillList<
        Config extends Alova2MethodConfig<ResultIPageBillVO> & {
          params: {
            /**
             * 账单列表查询参数
             */
            
            startDate?: string;
            endDate?: string;
            categoryId?: string;
            type?: string;
            paymentMethodId?: string;
            minAmount?: string;
            maxAmount?: string;
            keyword?: string;
            page?: number;
            size?: number;
            familyId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultIPageBillVO, 'bill.getPageBillList', Config>;
      /**
       * ---
       *
       * [GET] 获取月度统计
       *
       * **path:** /bill/monthly-stats
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单月度统计参数
       *   billMonthlyStatsDTO?: {
       *     // 月份，格式为YYYY-MM
       *     month: string
       *     // 家庭ID，用于查询家庭账单统计信息
       *     familyId?: string
       *   }
       *   month?: string
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单月度统计信息
       *   data?: {
       *     // 月份，格式为YYYY-MM
       *     month?: string
       *     // 支出金额
       *     expense?: string
       *     // 收入金额
       *     income?: string
       *     // 结余金额
       *     balance?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getMonthlyStats<
        Config extends Alova2MethodConfig<ResultBillMonthlyStatsVO> & {
          params: {
            /**
             * 账单月度统计参数
             */
            
            month?: string;
            familyId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillMonthlyStatsVO, 'bill.getMonthlyStats', Config>;
      /**
       * ---
       *
       * [GET] 获取账单详情
       *
       * **path:** /bill/detail
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单 ID
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单信息
       *   data?: {
       *     // 账单 ID
       *     id?: string
       *     // 账单名称
       *     name?: string
       *     // 分类信息
       *     category?: {
       *       // 分类 ID
       *       id?: string
       *       // 分类名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 分类类型：income-收入，expense-支出
       *       type?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 支付方式信息
       *     paymentMethod?: {
       *       // 支付方式 ID
       *       id?: string
       *       // 支付方式名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 账单类型：income-收入，expense-支出
       *     type?: string
       *     // 账单金额
       *     amount?: string
       *     // 账单时间
       *     time?: string
       *     // 账单备注
       *     remark?: string
       *     // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *     source?: string
       *     // 家庭 ID
       *     familyId?: string
       *     // 家庭名称
       *     familyName?: string
       *     // 记账人用户ID
       *     userId?: string
       *     // 记账人昵称
       *     userNickname?: string
       *     // 记账人头像
       *     userAvatar?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getBillDetail<
        Config extends Alova2MethodConfig<ResultBillVO> & {
          params: {
            /**
             * 账单 ID
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillVO, 'bill.getBillDetail', Config>;
      /**
       * ---
       *
       * [GET] 获取分类列表
       *
       * **path:** /bill/categories
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 分类类型：income-收入，expense-支出
       *   type?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 分类信息
       *   // [items] end
       *   data?: Array<{
       *     // 分类 ID
       *     id?: string
       *     // 分类名称
       *     name?: string
       *     // 图标 URL
       *     icon?: string
       *     // 分类类型：income-收入，expense-支出
       *     type?: string
       *     // 排序
       *     sortOrder?: number
       *     // 是否默认
       *     isDefault?: boolean
       *     // 用户 ID
       *     userId?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getCategories<
        Config extends Alova2MethodConfig<ResultListCategoryVO> & {
          params: {
            /**
             * 分类类型：income-收入，expense-支出
             */
            type?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListCategoryVO, 'bill.getCategories', Config>;
    };
    auth: {
      /**
       * ---
       *
       * [POST] 发送验证码
       *
       * **path:** /auth/send-code
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      sendCode<
        Config extends Alova2MethodConfig<ResultVoid> & {
          data: SendCodeDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultVoid, 'auth.sendCode', Config>;
      /**
       * ---
       *
       * [POST] 找回密码
       *
       * **path:** /auth/retrieve-password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 验证码
       *   code: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      retrievePassword<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: RetrievePasswordDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'auth.retrievePassword', Config>;
      /**
       * ---
       *
       * [POST] 登出
       *
       * **path:** /auth/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      logout<Config extends Alova2MethodConfig<ResultVoid>>(
        config?: Config
      ): Alova2Method<ResultVoid, 'auth.logout', Config>;
      /**
       * ---
       *
       * [POST] 微信登录
       *
       * **path:** /auth/login-wechat
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 微信登录 code
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 令牌响应
       *   data?: {
       *     // 访问令牌
       *     token?: string
       *     // 过期时间（毫秒）
       *     expireTime?: number
       *     // 用户 ID
       *     userId?: string
       *     // 用户昵称
       *     nickname?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      loginByWechat<
        Config extends Alova2MethodConfig<ResultTokenVO> & {
          data: LoginByWechatDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultTokenVO, 'auth.loginByWechat', Config>;
      /**
       * ---
       *
       * [POST] 手机号登录
       *
       * **path:** /auth/login-phone
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 验证码
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 令牌响应
       *   data?: {
       *     // 访问令牌
       *     token?: string
       *     // 过期时间（毫秒）
       *     expireTime?: number
       *     // 用户 ID
       *     userId?: string
       *     // 用户昵称
       *     nickname?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      loginByPhone<
        Config extends Alova2MethodConfig<ResultTokenVO> & {
          data: LoginByPhoneDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultTokenVO, 'auth.loginByPhone', Config>;
      /**
       * ---
       *
       * [POST] 密码登录
       *
       * **path:** /auth/login-password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 密码
       *   password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 令牌响应
       *   data?: {
       *     // 访问令牌
       *     token?: string
       *     // 过期时间（毫秒）
       *     expireTime?: number
       *     // 用户 ID
       *     userId?: string
       *     // 用户昵称
       *     nickname?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      loginByPassword<
        Config extends Alova2MethodConfig<ResultTokenVO> & {
          data: LoginByPasswordDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultTokenVO, 'auth.loginByPassword', Config>;
    };
    preference: {
      /**
       * ---
       *
       * [POST] 设置偏好
       *
       * **path:** /preference/set
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 偏好设置键
       *   key: string
       *   // 偏好设置值
       *   value: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      set<
        Config extends Alova2MethodConfig<ResultVoid> & {
          data: PreferenceSetDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultVoid, 'preference.set', Config>;
      /**
       * ---
       *
       * [DELETE] 删除偏好
       *
       * **path:** /preference/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 偏好设置键
       *   key: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<ResultVoid> & {
          params: {
            /**
             * 偏好设置键
             */
            key: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultVoid, 'preference.delete', Config>;
      /**
       * ---
       *
       * [GET] 获取偏好
       *
       * **path:** /preference/get
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 偏好设置键
       *   key: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: string
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<ResultString> & {
          params: {
            /**
             * 偏好设置键
             */
            key: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultString, 'preference.get', Config>;
      /**
       * ---
       *
       * [GET] 获取所有偏好
       *
       * **path:** /preference/all
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: Record<string, string>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getAll<Config extends Alova2MethodConfig<ResultRecordStringString>>(
        config?: Config
      ): Alova2Method<ResultRecordStringString, 'preference.getAll', Config>;
    };
    statistics: {
      /**
       * ---
       *
       * [GET] 获取月度统计概览
       *
       * **path:** /statistics/overview
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单月度统计参数
       *   dto?: {
       *     // 月份，格式为YYYY-MM
       *     month: string
       *     // 家庭ID，用于查询家庭账单统计信息
       *     familyId?: string
       *   }
       *   month?: string
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单月度统计信息
       *   data?: {
       *     // 月份，格式为YYYY-MM
       *     month?: string
       *     // 支出金额
       *     expense?: string
       *     // 收入金额
       *     income?: string
       *     // 结余金额
       *     balance?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getOverview<
        Config extends Alova2MethodConfig<ResultBillMonthlyStatsVO> & {
          params: {
            /**
             * 账单月度统计参数
             */
            dto?: BillMonthlyStatsDTO;
            month?: string;
            familyId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillMonthlyStatsVO, 'statistics.getOverview', Config>;
      /**
       * ---
       *
       * [GET] 获取成员账单统计
       *
       * **path:** /statistics/members-bill
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单月度统计参数
       *   dto?: {
       *     // 月份，格式为YYYY-MM
       *     month: string
       *     // 家庭ID，用于查询家庭账单统计信息
       *     familyId?: string
       *   }
       *   month?: string
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 家庭成员统计数据
       *   // [items] end
       *   data?: Array<{
       *     // 用户ID
       *     userId?: string
       *     // 用户昵称
       *     nickname?: string
       *     // 用户头像
       *     avatar?: string
       *     // 支出金额
       *     expense?: string
       *     // 收入金额
       *     income?: string
       *     // 支出占比(%)
       *     expensePercentage?: number
       *     // 收入占比(%)
       *     incomePercentage?: number
       *     // 是否是户主
       *     isOwner?: boolean
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getMembersStats<
        Config extends Alova2MethodConfig<ResultListFamilyMemberStatsVO> & {
          params: {
            /**
             * 账单月度统计参数
             */
            dto?: BillMonthlyStatsDTO;
            month?: string;
            familyId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListFamilyMemberStatsVO, 'statistics.getMembersStats', Config>;
      /**
       * ---
       *
       * [GET] 获取每日收支趋势
       *
       * **path:** /statistics/daily-trend
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单月度统计参数
       *   dto?: {
       *     // 月份，格式为YYYY-MM
       *     month: string
       *     // 家庭ID，用于查询家庭账单统计信息
       *     familyId?: string
       *   }
       *   month?: string
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 每日收支趋势
       *   // [items] end
       *   data?: Array<{
       *     // 日期，格式为YYYY-MM-DD
       *     date?: string
       *     // 支出金额
       *     expense?: string
       *     // 收入金额
       *     income?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getDailyTrend<
        Config extends Alova2MethodConfig<ResultListDailyTrendVO> & {
          params: {
            /**
             * 账单月度统计参数
             */
            dto?: BillMonthlyStatsDTO;
            month?: string;
            familyId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListDailyTrendVO, 'statistics.getDailyTrend', Config>;
      /**
       * ---
       *
       * [GET] 获取分类统计
       *
       * **path:** /statistics/category
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 分类统计参数
       *   dto?: {
       *     // 月份，格式为YYYY-MM
       *     month: string
       *     // 账单类型：income-收入，expense-支出
       *     type: string
       *     // 家庭ID，用于查询家庭账单统计信息
       *     familyId?: string
       *   }
       *   month?: string
       *   type?: string
       *   familyId?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 分类统计信息
       *   // [items] end
       *   data?: Array<{
       *     // 分类ID
       *     categoryId?: string
       *     // 分类名称
       *     categoryName?: string
       *     // 分类图标
       *     categoryIcon?: string
       *     // 金额
       *     amount?: string
       *     // 占比百分比
       *     percentage?: number
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getCategoryStats<
        Config extends Alova2MethodConfig<ResultListCategoryStatisticsVO> & {
          params: {
            /**
             * 分类统计参数
             */
            dto?: StatisticsCategoryDTO;
            month?: string;
            type?: string;
            familyId?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListCategoryStatisticsVO, 'statistics.getCategoryStats', Config>;
    };
    ai: {
      /**
       * ---
       *
       * [GET] 文本识别
       *
       * **path:** /ai/text
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   text: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单信息
       *   data?: {
       *     // 账单 ID
       *     id?: string
       *     // 账单名称
       *     name?: string
       *     // 分类信息
       *     category?: {
       *       // 分类 ID
       *       id?: string
       *       // 分类名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 分类类型：income-收入，expense-支出
       *       type?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 支付方式信息
       *     paymentMethod?: {
       *       // 支付方式 ID
       *       id?: string
       *       // 支付方式名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 账单类型：income-收入，expense-支出
       *     type?: string
       *     // 账单金额
       *     amount?: string
       *     // 账单时间
       *     time?: string
       *     // 账单备注
       *     remark?: string
       *     // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *     source?: string
       *     // 家庭 ID
       *     familyId?: string
       *     // 家庭名称
       *     familyName?: string
       *     // 记账人用户ID
       *     userId?: string
       *     // 记账人昵称
       *     userNickname?: string
       *     // 记账人头像
       *     userAvatar?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      text<
        Config extends Alova2MethodConfig<ResultBillVO> & {
          params: {
            text: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillVO, 'ai.text', Config>;
      /**
       * ---
       *
       * [GET] ocr识别
       *
       * **path:** /ai/ocr
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   fileId: string
       *   fileExt: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单信息
       *   data?: {
       *     // 账单 ID
       *     id?: string
       *     // 账单名称
       *     name?: string
       *     // 分类信息
       *     category?: {
       *       // 分类 ID
       *       id?: string
       *       // 分类名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 分类类型：income-收入，expense-支出
       *       type?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 支付方式信息
       *     paymentMethod?: {
       *       // 支付方式 ID
       *       id?: string
       *       // 支付方式名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 账单类型：income-收入，expense-支出
       *     type?: string
       *     // 账单金额
       *     amount?: string
       *     // 账单时间
       *     time?: string
       *     // 账单备注
       *     remark?: string
       *     // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *     source?: string
       *     // 家庭 ID
       *     familyId?: string
       *     // 家庭名称
       *     familyName?: string
       *     // 记账人用户ID
       *     userId?: string
       *     // 记账人昵称
       *     userNickname?: string
       *     // 记账人头像
       *     userAvatar?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      ocr<
        Config extends Alova2MethodConfig<ResultBillVO> & {
          params: {
            fileId: string;
            fileExt: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillVO, 'ai.ocr', Config>;
      /**
       * ---
       *
       * [GET] 分析
       *
       * **path:** /ai/analysis
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   analysisType: number
       *   month: string
       *   familyId?: string
       *   regenerate?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // AI分析结果
       *   data?: {
       *     // AI分析内容
       *     content?: string
       *     // 是否为缓存结果
       *     cached?: boolean
       *     // 今日剩余分析次数，-1表示无限制(VIP)
       *     remainingCount?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      analysis<
        Config extends Alova2MethodConfig<ResultAiAnalysisVO> & {
          params: {
            analysisType: number;
            month: string;
            familyId?: string;
            regenerate?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultAiAnalysisVO, 'ai.analysis', Config>;
    };
  }

  var Apis: Apis;
}
