/* tslint:disable */
/* eslint-disable */
/**
 * 小川记账接口文档 - version v1.0.0
 *
 * 小川记账接口文档
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface BillMonthlyStatsDTO {
  /**
   * 月份，格式为YYYY-MM
   */
  month: string;
  /**
   * 家庭ID，用于查询家庭账单统计信息
   */
  familyId?: string;
}
export interface BillListDTO {
  /**
   * 开始日期
   */
  startDate?: string;
  /**
   * 结束日期
   */
  endDate?: string;
  /**
   * 分类 ID
   */
  categoryId?: string;
  /**
   * 账单类型：income-收入，expense-支出，空字符串：全部
   */
  type?: 'income' | 'expense' | '';

  /**
   * 支付方式 ID
   */
  paymentMethodId?: string;

  /**
   * 最小金额
   */
  minAmount?: number;
  /**
   * 最大金额
   */
  maxAmount?: number;
  /**
   * 关键字模糊搜索，支持名称和备注
   */
  keyword?: string;
  /**
   * 页码
   */
  page: number;
  /**
   * 每页数量
   */
  size: number;
}
export interface UserProfileUpdateDTO {
  /**
   * 用户 ID
   */
  userId?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 头像 URL
   */
  avatar?: string;
  /**
   * 性别：0-未知，1-男，2-女
   */
  gender?: string;
}
export interface UpdatePasswordByOldDTO {
  /**
   * 用户 ID
   */
  userId: string;
  /**
   * 旧密码
   */
  oldPassword: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface UpdatePasswordByCodeDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码
   */
  code: string;
  /**
   * 新密码
   */
  newPassword: string;
}
export interface UpdateBillDTO {
  /**
   * 账单 ID
   */
  id: string;
  /**
   * 账单名称
   */
  name?: string;
  /**
   * 分类 ID
   */
  categoryId?: string;
  /**
   * 支付方式 ID
   */
  paymentMethodId?: string;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type?: string;
  /**
   * 账单时间
   */
  time?: string;
  /**
   * 账单金额
   */
  amount?: number;
  /**
   * 账单备注
   */
  remark?: string;
}
export interface AddBillDTO {
  /**
   * 账单名称
   */
  name: string;
  /**
   * 分类 ID
   */
  categoryId?: string;
  /**
   * 支付方式 ID
   */
  paymentMethodId?: string;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type: 'income' | 'expense';
  /**
   * 账单金额
   */
  amount: string;
  /**
   * 账单时间
   */
  time: string;
  /**
   * 账单备注
   */
  remark?: string;
  /**
   * 家庭 ID（可选）
   */
  familyId?: string;
  /**
   * 账单来源：manual-手动，ocr-图片识别，voice-语音
   */
  source?: string;
}
export interface SendCodeDTO {
  /**
   * 手机号
   */
  phone: string;
}
export interface LoginByPhoneDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 验证码
   */
  code: string;
}
export interface LoginByPasswordDTO {
  /**
   * 手机号
   */
  phone: string;
  /**
   * 密码
   */
  password: string;
}
export interface UserVO {
  /**
   * 用户 ID
   */
  id?: string;
  /**
   * 手机号
   */
  phone?: string;
  /**
   * 昵称
   */
  nickname?: string;
  /**
   * 头像 URL
   */
  avatar?: string;
  /**
   * 性别：0-未知，1-男，2-女
   */
  gender?: string;
  /**
   * 状态：false-禁用，true-正常
   */
  status?: boolean;
  /**
   * 最后登录时间
   */
  lastLoginTime?: string;
  /**
   * 创建时间
   */
  createTime?: string;
  /**
   * 更新时间
   */
  updateTime?: string;
}
export interface ResultUserVO {
  code?: number;
  message?: string;
  /**
   * 用户信息
   */
  data?: UserVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultBoolean {
  code?: number;
  message?: string;
  data?: boolean;
  timestamp?: number;
  success?: boolean;
}
export interface PaymentMethodVO {
  /**
   * 支付方式 ID
   */
  id?: string;
  /**
   * 支付方式名称
   */
  name?: string;
  /**
   * 图标 URL
   */
  icon?: string;
  /**
   * 排序
   */
  sortOrder?: number;
  /**
   * 是否默认
   */
  isDefault?: boolean;
  /**
   * 用户 ID
   */
  userId?: string;
}
export interface ResultListPaymentMethodVO {
  code?: number;
  message?: string;
  data?: PaymentMethodVO[];
  timestamp?: number;
  success?: boolean;
}
export interface TempFileVO {
  /**
   * 临时文件ID
   */
  fileId?: string;
  /**
   * 临时文件大小
   */
  fileSize?: number;
}
export interface ResultTempFileVO {
  code?: number;
  message?: string;
  /**
   * 临时文件信息
   */
  data?: TempFileVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultVoid {
  code?: number;
  message?: string;
  data?: null;
  timestamp?: number;
  success?: boolean;
}
export interface TokenVO {
  /**
   * 访问令牌
   */
  token?: string;
  /**
   * 过期时间（毫秒）
   */
  expireTime?: number;
  /**
   * 用户 ID
   */
  userId?: string;
  /**
   * 用户昵称
   */
  nickname?: string;
}
export interface ResultTokenVO {
  code?: number;
  message?: string;
  /**
   * 令牌响应
   */
  data?: TokenVO;
  timestamp?: number;
  success?: boolean;
}
export interface BillMonthlyStatsVO {
  /**
   * 月份，格式为YYYY-MM
   */
  month?: string;
  /**
   * 支出金额
   */
  expense?: number;
  /**
   * 收入金额
   */
  income?: number;
  /**
   * 结余金额
   */
  balance?: number;
}
export interface ResultBillMonthlyStatsVO {
  code?: number;
  message?: string;
  /**
   * 账单月度统计信息
   */
  data?: BillMonthlyStatsVO;
  timestamp?: number;
  success?: boolean;
}
export interface CategoryVO {
  /**
   * 分类 ID
   */
  id?: string;
  /**
   * 分类名称
   */
  name?: string;
  /**
   * 图标 URL
   */
  icon?: string;
  /**
   * 分类类型：income-收入，expense-支出
   */
  type?: string;
  /**
   * 排序
   */
  sortOrder?: number;
  /**
   * 是否默认
   */
  isDefault?: boolean;
  /**
   * 用户 ID
   */
  userId?: string;
}
export interface BillVO {
  /**
   * 账单 ID
   */
  id?: string;
  /**
   * 账单名称
   */
  name?: string;
  /**
   * 分类信息
   */
  category?: CategoryVO;
  /**
   * 支付方式信息
   */
  paymentMethod?: PaymentMethodVO;
  /**
   * 账单类型：income-收入，expense-支出
   */
  type?: 'income' | 'expense';
  /**
   * 账单金额
   */
  amount?: string;
  /**
   * 账单时间
   */
  time?: string;
  /**
   * 账单备注
   */
  remark?: string;
  /**
   * 账单来源：manual-手动，ocr-图片识别，voice-语音
   */
  source?: string;
  /**
   * 家庭 ID
   */
  familyId?: string;
}
export interface IPageBillVO {
  size?: number;
  records?: BillVO[];
  current?: number;
  total?: number;
  /**
   * @deprecated
   */
  pages?: number;
}
export interface ResultIPageBillVO {
  code?: number;
  message?: string;
  data?: IPageBillVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultBillVO {
  code?: number;
  message?: string;
  /**
   * 账单信息
   */
  data?: BillVO;
  timestamp?: number;
  success?: boolean;
}
export interface ResultListCategoryVO {
  code?: number;
  message?: string;
  data?: CategoryVO[];
  timestamp?: number;
  success?: boolean;
}
declare global {
  interface Apis {
    user: {
      /**
       * ---
       *
       * [POST] 更新用户资料
       *
       * **path:** /user/updateProfile
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 用户 ID
       *   userId?: string
       *   // 昵称
       *   nickname?: string
       *   // 头像 URL
       *   avatar?: string
       *   // 性别：0-未知，1-男，2-女
       *   gender?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updateProfile<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UserProfileUpdateDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updateProfile', Config>;
      /**
       * ---
       *
       * [POST] 通过旧密码修改密码
       *
       * **path:** /user/updatePasswordByOld
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 用户 ID
       *   userId: string
       *   // 旧密码
       *   oldPassword: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updatePasswordByOld<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdatePasswordByOldDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updatePasswordByOld', Config>;
      /**
       * ---
       *
       * [POST] 通过验证码修改密码
       *
       * **path:** /user/updatePasswordByCode
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 验证码
       *   code: string
       *   // 新密码
       *   newPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updatePasswordByCode<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdatePasswordByCodeDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'user.updatePasswordByCode', Config>;
      /**
       * ---
       *
       * [GET] 获取用户资料
       *
       * **path:** /user/profile
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 用户信息
       *   data?: {
       *     // 用户 ID
       *     id?: string
       *     // 手机号
       *     phone?: string
       *     // 昵称
       *     nickname?: string
       *     // 头像 URL
       *     avatar?: string
       *     // 性别：0-未知，1-男，2-女
       *     gender?: string
       *     // 状态：false-禁用，true-正常
       *     status?: boolean
       *     // 最后登录时间
       *     lastLoginTime?: string
       *     // 创建时间
       *     createTime?: string
       *     // 更新时间
       *     updateTime?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getProfile<Config extends Alova2MethodConfig<ResultUserVO>>(
        config?: Config
      ): Alova2Method<ResultUserVO, 'user.getProfile', Config>;
      /**
       * ---
       *
       * [GET] 检查是否设置了密码
       *
       * **path:** /user/hasPassword
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      hasPassword<Config extends Alova2MethodConfig<ResultBoolean>>(
        config?: Config
      ): Alova2Method<ResultBoolean, 'user.hasPassword', Config>;
    };
    file: {
      /**
       * ---
       *
       * [POST] 上传临时文件
       *
       * **path:** /file/uploadTempFile
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   file: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 临时文件信息
       *   data?: {
       *     // 临时文件ID
       *     fileId?: string
       *     // 临时文件大小
       *     fileSize?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      uploadTempFile<
        Config extends Alova2MethodConfig<ResultTempFileVO> & {
          params: {
            file: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultTempFileVO, 'file.uploadTempFile', Config>;
    };
    bill: {
      /**
       * ---
       *
       * [POST] 更新账单
       *
       * **path:** /bill/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 账单 ID
       *   id: string
       *   // 账单名称
       *   name?: string
       *   // 分类 ID
       *   categoryId?: string
       *   // 支付方式 ID
       *   paymentMethodId?: string
       *   // 账单类型：income-收入，expense-支出
       *   type?: string
       *   // 账单时间
       *   time?: string
       *   // 账单金额
       *   amount?: number
       *   // 账单备注
       *   remark?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      updateBill<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: UpdateBillDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'bill.updateBill', Config>;
      /**
       * ---
       *
       * [POST] 删除账单
       *
       * **path:** /bill/delete
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单 ID
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      deleteBill<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          params: {
            /**
             * 账单 ID
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'bill.deleteBill', Config>;
      /**
       * ---
       *
       * [POST] 添加账单
       *
       * **path:** /bill/add
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 账单名称
       *   name: string
       *   // 分类 ID
       *   categoryId: string
       *   // 支付方式 ID
       *   paymentMethodId?: string
       *   // 账单类型：income-收入，expense-支出
       *   type: string
       *   // 账单金额
       *   amount: number
       *   // 账单时间
       *   time: string
       *   // 账单备注
       *   remark?: string
       *   // 家庭 ID（可选）
       *   familyId?: string
       *   // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *   source?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: boolean
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      addBill<
        Config extends Alova2MethodConfig<ResultBoolean> & {
          data: AddBillDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultBoolean, 'bill.addBill', Config>;
      /**
       * ---
       *
       * [GET] 获取支付方式列表
       *
       * **path:** /bill/payment-methods
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 支付方式信息
       *   // [items] end
       *   data?: Array<{
       *     // 支付方式 ID
       *     id?: string
       *     // 支付方式名称
       *     name?: string
       *     // 图标 URL
       *     icon?: string
       *     // 排序
       *     sortOrder?: number
       *     // 是否默认
       *     isDefault?: boolean
       *     // 用户 ID
       *     userId?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getPaymentMethods<Config extends Alova2MethodConfig<ResultListPaymentMethodVO>>(
        config?: Config
      ): Alova2Method<ResultListPaymentMethodVO, 'bill.getPaymentMethods', Config>;
      /**
       * ---
       *
       * [GET] 获取月度统计
       *
       * **path:** /bill/monthly-stats
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单月度统计参数
       *   billMonthlyStatsDTO: {
       *     // 月份，格式为YYYY-MM
       *     month: string
       *     // 家庭ID，用于查询家庭账单统计信息
       *     familyId?: string
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单月度统计信息
       *   data?: {
       *     // 月份，格式为YYYY-MM
       *     month?: string
       *     // 支出金额
       *     expense?: number
       *     // 收入金额
       *     income?: number
       *     // 结余金额
       *     balance?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getMonthlyStats<
        Config extends Alova2MethodConfig<ResultBillMonthlyStatsVO> & {
          params: {
            /**
             * 账单月度统计参数
             */
            billMonthlyStatsDTO: BillMonthlyStatsDTO;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillMonthlyStatsVO, 'bill.getMonthlyStats', Config>;
      /**
       * ---
       *
       * [GET] 获取账单列表
       *
       * **path:** /bill/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单列表查询参数
       *   billListDTO: {
       *     // 开始日期
       *     startDate?: string
       *     // 结束日期
       *     endDate?: string
       *     // 分类 ID
       *     categoryId?: string
       *     // 账单类型：income-收入，expense-支出，空字符串：全部
       *     type?: string
       *     // 最小金额
       *     minAmount?: number
       *     // 最大金额
       *     maxAmount?: number
       *     // 关键字模糊搜索，支持名称和备注
       *     keyword?: string
       *     // 页码
       *     page: number
       *     // 每页数量
       *     size: number
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: {
       *     size?: number
       *     // [items] start
       *     // 账单信息
       *     // [items] end
       *     records?: Array<{
       *       // 账单 ID
       *       id?: string
       *       // 账单名称
       *       name?: string
       *       // 分类信息
       *       category?: {
       *         // 分类 ID
       *         id?: string
       *         // 分类名称
       *         name?: string
       *         // 图标 URL
       *         icon?: string
       *         // 分类类型：income-收入，expense-支出
       *         type?: string
       *         // 排序
       *         sortOrder?: number
       *         // 是否默认
       *         isDefault?: boolean
       *         // 用户 ID
       *         userId?: string
       *       }
       *       // 支付方式信息
       *       paymentMethod?: {
       *         // 支付方式 ID
       *         id?: string
       *         // 支付方式名称
       *         name?: string
       *         // 图标 URL
       *         icon?: string
       *         // 排序
       *         sortOrder?: number
       *         // 是否默认
       *         isDefault?: boolean
       *         // 用户 ID
       *         userId?: string
       *       }
       *       // 账单类型：income-收入，expense-支出
       *       type?: string
       *       // 账单金额
       *       amount?: number
       *       // 账单时间
       *       time?: string
       *       // 账单备注
       *       remark?: string
       *       // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *       source?: string
       *       // 家庭 ID
       *       familyId?: string
       *     }>
       *     current?: number
       *     total?: number
       *     // [deprecated]
       *     pages?: number
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getBillList<
        Config extends Alova2MethodConfig<ResultIPageBillVO> & {
          params: BillListDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultIPageBillVO, 'bill.getBillList', Config>;
      /**
       * ---
       *
       * [GET] 获取账单详情
       *
       * **path:** /bill/detail
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 账单 ID
       *   id: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单信息
       *   data?: {
       *     // 账单 ID
       *     id?: string
       *     // 账单名称
       *     name?: string
       *     // 分类信息
       *     category?: {
       *       // 分类 ID
       *       id?: string
       *       // 分类名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 分类类型：income-收入，expense-支出
       *       type?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 支付方式信息
       *     paymentMethod?: {
       *       // 支付方式 ID
       *       id?: string
       *       // 支付方式名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 账单类型：income-收入，expense-支出
       *     type?: string
       *     // 账单金额
       *     amount?: number
       *     // 账单时间
       *     time?: string
       *     // 账单备注
       *     remark?: string
       *     // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *     source?: string
       *     // 家庭 ID
       *     familyId?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getBillDetail<
        Config extends Alova2MethodConfig<ResultBillVO> & {
          params: {
            /**
             * 账单 ID
             */
            id: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillVO, 'bill.getBillDetail', Config>;
      /**
       * ---
       *
       * [GET] 获取分类列表
       *
       * **path:** /bill/categories
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 分类类型：income-收入，expense-支出
       *   type?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // [items] start
       *   // 分类信息
       *   // [items] end
       *   data?: Array<{
       *     // 分类 ID
       *     id?: string
       *     // 分类名称
       *     name?: string
       *     // 图标 URL
       *     icon?: string
       *     // 分类类型：income-收入，expense-支出
       *     type?: string
       *     // 排序
       *     sortOrder?: number
       *     // 是否默认
       *     isDefault?: boolean
       *     // 用户 ID
       *     userId?: string
       *   }>
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      getCategories<
        Config extends Alova2MethodConfig<ResultListCategoryVO> & {
          params: {
            /**
             * 分类类型：income-收入，expense-支出
             */
            type?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultListCategoryVO, 'bill.getCategories', Config>;
    };
    auth: {
      /**
       * ---
       *
       * [POST] 发送验证码
       *
       * **path:** /auth/sendCode
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   data?: null
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      sendCode<
        Config extends Alova2MethodConfig<ResultVoid> & {
          data: SendCodeDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultVoid, 'auth.sendCode', Config>;
      /**
       * ---
       *
       * [POST] 手机号登录
       *
       * **path:** /auth/loginByPhone
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 验证码
       *   code: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 令牌响应
       *   data?: {
       *     // 访问令牌
       *     token?: string
       *     // 过期时间（毫秒）
       *     expireTime?: number
       *     // 用户 ID
       *     userId?: string
       *     // 用户昵称
       *     nickname?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      loginByPhone<
        Config extends Alova2MethodConfig<ResultTokenVO> & {
          data: LoginByPhoneDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultTokenVO, 'auth.loginByPhone', Config>;
      /**
       * ---
       *
       * [POST] 密码登录
       *
       * **path:** /auth/loginByPassword
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 手机号
       *   phone: string
       *   // 密码
       *   password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 令牌响应
       *   data?: {
       *     // 访问令牌
       *     token?: string
       *     // 过期时间（毫秒）
       *     expireTime?: number
       *     // 用户 ID
       *     userId?: string
       *     // 用户昵称
       *     nickname?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      loginByPassword<
        Config extends Alova2MethodConfig<ResultTokenVO> & {
          data: LoginByPasswordDTO;
        }
      >(
        config: Config
      ): Alova2Method<ResultTokenVO, 'auth.loginByPassword', Config>;
    };
    ai: {
      /**
       * ---
       *
       * [GET] ocr
       *
       * **path:** /ai/ocr
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   fileId: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code?: number
       *   message?: string
       *   // 账单信息
       *   data?: {
       *     // 账单 ID
       *     id?: string
       *     // 账单名称
       *     name?: string
       *     // 分类信息
       *     category?: {
       *       // 分类 ID
       *       id?: string
       *       // 分类名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 分类类型：income-收入，expense-支出
       *       type?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 支付方式信息
       *     paymentMethod?: {
       *       // 支付方式 ID
       *       id?: string
       *       // 支付方式名称
       *       name?: string
       *       // 图标 URL
       *       icon?: string
       *       // 排序
       *       sortOrder?: number
       *       // 是否默认
       *       isDefault?: boolean
       *       // 用户 ID
       *       userId?: string
       *     }
       *     // 账单类型：income-收入，expense-支出
       *     type?: string
       *     // 账单金额
       *     amount?: number
       *     // 账单时间
       *     time?: string
       *     // 账单备注
       *     remark?: string
       *     // 账单来源：manual-手动，ocr-图片识别，voice-语音
       *     source?: string
       *     // 家庭 ID
       *     familyId?: string
       *   }
       *   timestamp?: number
       *   success?: boolean
       * }
       * ```
       */
      ocr<
        Config extends Alova2MethodConfig<ResultBillVO> & {
          params: {
            fileId: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<ResultBillVO, 'ai.ocr', Config>;
    };
  }

  var Apis: Apis;
}
