// 账单来源
export const SOURCE_MAP = {
  manual: '手动添加',
  ocr: '图片识别',
  voice: '语音输入',
}

// 支付方式列表
export const LOCAL_PAYMENT_METHOD_LIST = [
  {
    id: 'pay_001',
    name: '微信',
    icon: 'i-mingcute:wechat-pay-line text-[#07c160]',
    sortOrder: 1,
    isDefault: true,
  },
  {
    id: 'pay_002',
    name: '支付宝',
    icon: 'i-mingcute:alipay-line text-[#1677ff]',
    sortOrder: 2,
    isDefault: true,
  },
  {
    id: 'pay_003',
    name: '现金',
    icon: 'i-mingcute:cash-line text-[#f1c305]',
    sortOrder: 3,
    isDefault: true,
  },
  {
    id: 'pay_004',
    name: '银行卡',
    icon: 'i-mingcute:bank-card-line text-[#50f4ff]',
    sortOrder: 4,
    isDefault: true,
  },
  {
    id: 'pay_005',
    name: '信用卡',
    icon: 'i-lucide:credit-card text-[#8ba6c5]',
    sortOrder: 5,
    isDefault: true,
  },
  {
    id: 'pay_006',
    name: '其他',
    icon: 'i-icon-park-outline:payment-method text-[#ff4d4f]',
    sortOrder: 6,
    isDefault: true,
  },
]

// 消费类型列表
export const LOCAL_PAY_CATEGORY_LIST = [
  {
    id: 'cat_exp_001',
    name: '餐饮',
    icon: 'i-icon-park-outline:chopsticks-fork',
    type: 'expense',
    sortOrder: 1,
    isDefault: true,
  },
  {
    id: 'cat_exp_002',
    name: '购物',
    icon: 'i-mingcute:shopping-bag-1-line',
    type: 'expense',
    sortOrder: 2,
    isDefault: true,
  },
  {
    id: 'cat_exp_003',
    name: '交通',
    icon: 'i-mingcute:car-3-line',
    type: 'expense',
    sortOrder: 3,
    isDefault: true,
  },
  {
    id: 'cat_exp_004',
    name: '娱乐',
    icon: 'i-mingcute:movie-line',
    type: 'expense',
    sortOrder: 4,
    isDefault: true,
  },
  {
    id: 'cat_exp_005',
    name: '居住',
    icon: 'i-lucide:house-plug',
    type: 'expense',
    sortOrder: 5,
    isDefault: true,
  },
  {
    id: 'cat_exp_006',
    name: '通讯',
    icon: 'i-lucide:smartphone-charging',
    type: 'expense',
    sortOrder: 6,
    isDefault: true,
  },
  {
    id: 'cat_exp_007',
    name: '医疗',
    icon: 'i-lucide:hospital',
    type: 'expense',
    sortOrder: 7,
    isDefault: true,
  },
  {
    id: 'cat_exp_008',
    name: '教育',
    icon: 'i-lucide:book-open',
    type: 'expense',
    sortOrder: 8,
    isDefault: true,
  },
  {
    id: 'cat_exp_009',
    name: '其他支出',
    icon: 'i-icon-park-outline:expenses',
    type: 'expense',
    sortOrder: 9,
    isDefault: true,
  },
  {
    id: 'cat_inc_001',
    name: '工资',
    icon: 'i-mingcute:currency-dollar-line',
    type: 'income',
    sortOrder: 1,
    isDefault: true,
  },
  {
    id: 'cat_inc_002',
    name: '奖金',
    icon: 'i-material-symbols:money-bag-outline-rounded',
    type: 'income',
    sortOrder: 2,
    isDefault: true,
  },
  {
    id: 'cat_inc_003',
    name: '投资',
    icon: 'i-carbon:financial-assets',
    type: 'income',
    sortOrder: 3,
    isDefault: true,
  },
  {
    id: 'cat_inc_004',
    name: '兼职',
    icon: 'i-material-symbols:deployed-code-account-outline-rounded',
    type: 'income',
    sortOrder: 4,
    isDefault: true,
  },
  {
    id: 'cat_inc_005',
    name: '礼金',
    icon: 'i-mingcute:gift-line',
    type: 'income',
    sortOrder: 5,
    isDefault: true,
  },
  {
    id: 'cat_inc_006',
    name: '退款',
    icon: 'i-mingcute:card-refund-line',
    type: 'income',
    sortOrder: 6,
    isDefault: true,
  },
  {
    id: 'cat_inc_007',
    name: '其他收入',
    icon: 'i-icon-park-outline:income',
    type: 'income',
    sortOrder: 7,
    isDefault: true,
  },
]
